import { Inter,Nunito } from "next/font/google";
import './global.css'

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
